resolver: lts-18.28

packages:
- .

extra-deps:
- github: quanterall/qtility
  commit: feebd3658c48ca15caea9007f2a545019a246521
  subdirs:
  - qtility
  - qtility-db
  # nix-sha256: sha256-GKn9DqlG5TdJVoUXRaYxXN8UPxgSq/coswpc4O049Eg=

nix:
  enable: false
  packages: 
  - zlib
  - postgresql
