resolver: lts-18.14

packages:
- .

extra-deps:
- github: quanterall/qtility
  commit: aac174d0d953a5bd04dc75c80977dc5b0e0939bf
  subdirs:
  - qtility
  - qtility-db
  # nix-sha256: sha256-VeYLRJnciju2VJDeb8RG8L8qQ9cw5nuivHCEQkAwSb4=

nix:
  enable: false
  packages: 
  - zlib
  - postgresql
