resolver: lts-18.14

packages:
- .

extra-deps:
- github: quanterall/qtility
  commit: 35c57646d5be4c40c1d6b838fccde248f3307ee4
  subdirs:
  - qtility
  # nix-sha256: sha256-72Rou56tjbkhKna3lW/CzftIiqu+LHoHOM1W2+eSZEc=

nix:
  enable: false
  packages: 
  - zlib
  - postgresql
