resolver: lts-18.14

packages:
- .

extra-deps:
- github: quanterall/qtility
  commit: 9e4d1ffc12aa349dfd3ce72c8216cad4eee4a69b
  subdirs:
  - qtility
  # nix-sha256: sha256-vS92TIgF99So9tg/w60eCdpgl1NkMvTeN1mac8CpeVY=

nix:
  enable: false
  packages: 
  - zlib
  - postgresql
