resolver: lts-18.14

packages:
- .

extra-deps:
- github: quanterall/qtility
  commit: 42983c33a3a521eda39a9e8603e567b7fbc905a9
  subdirs:
  - qtility
  # nix-sha256: sha256-VLr/KVEhRjMM3lq6bfwfzkfOorbEicU/Wb+gvx2tOCU=

nix:
  enable: false
  packages: 
  - zlib
  - postgresql
